[versions]
androidGradlePlugin = "8.11.0"
commonsValidator = "1.9.0"
dexmakerMockitoInlineExtended = "2.28.4"
gradleVersionsPlugin = "0.48.0"
desugarJdkLibs = "2.0.4"
kotlin = "2.0.0"
kotlinKsp = "2.0.0-1.0.22"
coroutines = "1.8.0"
koin = "3.4.3"
composeLifecycleViewModel = "2.8.5"
junit = "4.13.2"
mockitoCore = "5.12.0"
mockitoKotlin = "5.3.1"
truth = "1.1.5"
androidxJUnit = "1.2.1"
espresso = "3.6.1"
turbine = "0.5.1"
androidTestsRunner = "1.6.1"
androidTestRules = "1.6.1"
androidTestKtx = "1.6.1"
androidTestIntents = "3.6.1"
mockitoAndroid = "5.12.0"
espressoIdlingResource = "3.6.1"
ktlint = "12.2.0"
detekt = "1.23.8"
leakcanary = "2.12"
kover = "0.5.1"
dependencyAnalysis = "2.17.0"
licensee = "1.8.0"
dokka = "1.9.20"
androidXcore = "1.13.1"
appcompat = "1.7.1"
constraintLayout = "2.1.4"
navigation = "2.7.7"
security = "1.1.0-alpha06"
biometric = "1.2.0-alpha05"
fragment = "1.8.1"
activity = "1.9.0"
cameraX = "1.3.4"
cameraView = "1.3.4"
lifecycle = "2.8.3"
swiperefresh = "1.1.0"
appStartUp = "1.1.1"
splashScreen = "1.1.0-rc01"
cameraXMlVision = "1.4.0-rc02"
material = "1.14.0-alpha03"
retrofit = "2.11.0"
okHttp = "4.12.0"
timber = "5.0.1"
mlkit = "17.3.0"
zxing = "4.3.0"
gson = "2.11.0"
appDistribution = "5.0.0"
coil = "3.0.4"
fastAdapterCore = "5.7.0"
fastAdapterCoreAnimators = "1.1.0"
easylauncher = "6.4.0"
fusionauthJwt = "5.3.0"
serializationJson = "1.6.0"
serializationCore = "1.8.1"
roomCore = "2.6.1"
sqliteCipher = "4.6.1"
sqlite = "2.4.0"
roomTesting = "2.6.1"
yubikitAndroid = "2.8.0"
pinentry = "2.0.6"
balloon = "1.5.4"
rootbeer = "0.1.1"
playStorePublisher = "3.7.0"
inAppUpdate = "2.1.0"
inAppReview = "2.0.1"
okio = "3.5.0"
otp = "2.4.0"
apacheCommonsCodec = "1.16.0"
jsonSchemaFriend = "0.12.5"
jsonPath = "2.9.0"
jsonAssert = "2.0-rc1"
snyk = "0.7.0"
androidxComposeBom = "2025.04.00"
nlopez-compose-rulset = "0.4.22"
accompanist-drawablepainer = "0.37.3"
nav3Core = "1.0.0-alpha05"
nav3ViewModel = "1.0.0-alpha03"
paging-compose = "3.3.6"

[libraries]
commons-validator = { module = "commons-validator:commons-validator", version.ref = "commonsValidator" }
desugar-jdklibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" }
dexmaker-mockito-inline-extended = { module = "com.linkedin.dexmaker:dexmaker-mockito-inline-extended", version.ref = "dexmakerMockitoInlineExtended" }
licensee = { group = "app.cash.licensee", name = "licensee-gradle-plugin", version.ref = "licensee" }
koin = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
koin-test-junit = { group = "io.insert-koin", name = "koin-test-junit4", version.ref = "koin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-serializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serializationCore" }
kotlin-serializationjson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
mockito-android = { group = "org.mockito", name = "mockito-android", version.ref = "mockitoAndroid" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJUnit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
android-tests-runner = { group = "androidx.test", name = "runner", version.ref = "androidTestsRunner" }
android-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidTestRules" }
android-test-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "androidTestKtx" }
android-test-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "androidTestIntents" }
espresso-idling-resource = { group = "androidx.test.espresso", name = "espresso-idling-resource", version.ref = "espressoIdlingResource" }
leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidXcore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
security = { group = "androidx.security", name = "security-crypto", version.ref = "security" }
biometric = { group = "androidx.biometric", name = "biometric-ktx", version.ref = "biometric" }
fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
camerax = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraX" }
camerax-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraX" }
camerax-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraView" }
camerax-mlvision = { group = "androidx.camera", name = "camera-mlkit-vision", version.ref = "cameraXMlVision" }
lifecycle-annotationprocessor = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle" }
swiperefresh = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefresh" }
app-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "appStartUp" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gsonconverter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-scalarsconverter = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okHttp" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
qr-scan = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "mlkit" }
qr-generation = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxing" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
coil-networking = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
coil-views = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
fastadapter-core = { group = "com.mikepenz", name = "fastadapter", version.ref = "fastAdapterCore" }
fastadapter-binding = { group = "com.mikepenz", name = "fastadapter-extensions-binding", version.ref = "fastAdapterCore" }
fastadapter-utils = { group = "com.mikepenz", name = "fastadapter-extensions-utils", version.ref = "fastAdapterCore" }
fastadapter-diff = { group = "com.mikepenz", name = "fastadapter-extensions-diff", version.ref = "fastAdapterCore" }
fastadapter-expandable = { group = "com.mikepenz", name = "fastadapter-extensions-expandable", version.ref = "fastAdapterCore" }
fastadapter-ui = { group = "com.mikepenz", name = "fastadapter-extensions-ui", version.ref = "fastAdapterCore" }
fastadapter-animators = { group = "com.mikepenz", name = "itemanimators", version.ref = "fastAdapterCoreAnimators" }
easylauncher = { group = "com.project.starter", name = "easylauncher", version.ref = "easylauncher" }
fusionauth-jwt = { group = "io.fusionauth", name = "fusionauth-jwt", version.ref = "fusionauthJwt" }
room-core = { group = "androidx.room", name = "room-ktx", version.ref = "roomCore" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomCore" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "roomCore" }
sqlite-cipher = { group = "net.zetetic", name = "sqlcipher-android", version.ref = "sqliteCipher" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCore" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "roomTesting" }
sqlite = { group = "androidx.sqlite", name = "sqlite-ktx", version.ref = "sqlite" }
yubikit-android = { group = "com.yubico.yubikit", name = "android", version.ref = "yubikitAndroid" }
balloon = { group = "com.github.skydoves", name = "balloon", version.ref = "balloon" }
pinentry = { group = "com.alimuzaffar.lib", name = "pinentryedittext", version.ref = "pinentry" }
rootbeer = { group = "com.scottyab", name = "rootbeer-lib", version.ref = "rootbeer" }
inappupdate-core = { group = "com.google.android.play", name = "app-update", version.ref = "inAppUpdate" }
inappupdate-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "inAppUpdate" }
inappreview-core = { group = "com.google.android.play", name = "review", version.ref = "inAppReview" }
inappreview-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "inAppReview" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
otp = { group = "dev.turingcomplete", name = "kotlin-onetimepassword", version.ref = "otp" }
apache-commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "apacheCommonsCodec" }
jsonschema-friend = { group = "net.jimblackler.jsonschemafriend", name = "core", version.ref = "jsonSchemaFriend" }
json-path = { group = "com.jayway.jsonpath", name = "json-path", version.ref = "jsonPath" }
json-assert = { group = "org.skyscreamer", name = "jsonassert", version.ref = "jsonAssert" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "composeLifecycleViewModel" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics-android" }
compose-activity = { module = "androidx.activity:activity-compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ktlint-compose-rulset = { module = "io.nlopez.compose.rules:ktlint", version.ref = "nlopez-compose-rulset" }
detekt-compose-rulset = { module = "io.nlopez.compose.rules:detekt", version.ref = "nlopez-compose-rulset" }
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist-drawablepainer" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "nav3ViewModel" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging-compose" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-compose" }

[plugins]
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-gradle = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionsPlugin" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
app-distribution = { id = "com.google.firebase.appdistribution", version.ref = "appDistribution" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
playstore-publisher = { id = "com.github.triplet.play", version.ref = "playStorePublisher" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlinKsp" }
room = { id = "androidx.room", version.ref = "roomCore" }
snyk = { id = "io.snyk.gradle.plugin.snykplugin", version.ref = "snyk" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
